version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14 # or whichever version you prefer

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
